#!/bin/sh

set -e

. ./common.sh

volume_host_folder=$(local_volume_directory "$1")
mkdir -p $volume_host_folder

docker run -d --rm --name "da-pgis-$1" -p 127.0.0.1:5432:5432 -v "$volume_host_folder:/var/lib/postgresql/data" da-pgis

